version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  mongodb_data:


#  docker-compose up -d to start up these services
