export const ErrorCode = {
  ACCESS_RESTRICTED: 'ACCESS_RESTRICTED',
  UNSUPPORTED_PAYMENT_TYPE: 'UNSUPPORTED_PAYMENT_TYPE',
  SERVER_ERROR: 'SERVER_ERROR',
  REQUEST_FAILED: 'REQUEST_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  KYC_COMPLETENESS: 'KYC_COMPLETENESS',
  RATES_UNSUPPORTED: 'RATES_UNSUPPORTED',
  PROCESSOR_ERROR: 'PROCESSOR_ERROR',
  WALLET_DEBIT_FAILED: 'WALLET_DEBIT_FAILED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
};
